### ISSUE TITLE
Agregar excepciones para falta de folios. Utilizar la clase BoletaSinFoliosException

### ISSUE THREAD

**Issue by tomaspemora** [eol-uchile/ecommerce#20]
https://github.com/eol-uchile/ecommerce/blob/b2ed7a8b3a35447fa8847ea803408322f6468209/ecommerce/extensions/payment/boleta.py#L182C5-L183C1

Usar el status_code 412 junto con el mensaje que contenga el string "folio". Ejemplo:

![image](https://github.com/eol-uchile/ecommerce/assets/7586321/18b021c4-7ba1-4738-8c9b-b4713190d9b8)

**Comment by fsologureng** [comment]
El código ya hace lo que indica cuando envía el email.
